CREATE TABLE [dbo].[RESERVATION]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL, 
    [NB_PLACES] INT NOT NULL, 
    [EVENTS_GUID] UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [PK_RESERVATION] PRIMARY KEY CLUSTERED ([GUID] ASC),
	CONSTRAINT [FK_EVENTS_GUID] FOREIGN KEY ([EVENTS_GUID]) REFERENCES [dbo].[EVENTS] ([GUID])
)
