//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceAgenda {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtisteWS", Namespace="http://schemas.datacontract.org/2004/07/WebServiceAgenda.Business")]
    [System.SerializableAttribute()]
    public partial class ArtisteWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EvenementWS", Namespace="http://schemas.datacontract.org/2004/07/WebServiceAgenda.Business")]
    [System.SerializableAttribute()]
    public partial class EvenementWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceAgenda.ArtisteWS ArtistesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConcertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DispositionParticuliereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DureeEnMinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NombreLogesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NombreOeuvresExposeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TarifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceAgenda.ArtisteWS Artistes {
            get {
                return this.ArtistesField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistesField, value) != true)) {
                    this.ArtistesField = value;
                    this.RaisePropertyChanged("Artistes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Concert {
            get {
                return this.ConcertField;
            }
            set {
                if ((this.ConcertField.Equals(value) != true)) {
                    this.ConcertField = value;
                    this.RaisePropertyChanged("Concert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DispositionParticuliere {
            get {
                return this.DispositionParticuliereField;
            }
            set {
                if ((this.DispositionParticuliereField.Equals(value) != true)) {
                    this.DispositionParticuliereField = value;
                    this.RaisePropertyChanged("DispositionParticuliere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DureeEnMinutes {
            get {
                return this.DureeEnMinutesField;
            }
            set {
                if ((this.DureeEnMinutesField.Equals(value) != true)) {
                    this.DureeEnMinutesField = value;
                    this.RaisePropertyChanged("DureeEnMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NombreLoges {
            get {
                return this.NombreLogesField;
            }
            set {
                if ((this.NombreLogesField.Equals(value) != true)) {
                    this.NombreLogesField = value;
                    this.RaisePropertyChanged("NombreLoges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NombreOeuvresExposees {
            get {
                return this.NombreOeuvresExposeesField;
            }
            set {
                if ((this.NombreOeuvresExposeesField.Equals(value) != true)) {
                    this.NombreOeuvresExposeesField = value;
                    this.RaisePropertyChanged("NombreOeuvresExposees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Tarif {
            get {
                return this.TarifField;
            }
            set {
                if ((this.TarifField.Equals(value) != true)) {
                    this.TarifField = value;
                    this.RaisePropertyChanged("Tarif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LieuWS", Namespace="http://schemas.datacontract.org/2004/07/WebServiceAgenda.Business")]
    [System.SerializableAttribute()]
    public partial class LieuWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float LocationPercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbPlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebSiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float LocationPercent {
            get {
                return this.LocationPercentField;
            }
            set {
                if ((this.LocationPercentField.Equals(value) != true)) {
                    this.LocationPercentField = value;
                    this.RaisePropertyChanged("LocationPercent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbPlaces {
            get {
                return this.NbPlacesField;
            }
            set {
                if ((this.NbPlacesField.Equals(value) != true)) {
                    this.NbPlacesField = value;
                    this.RaisePropertyChanged("NbPlaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebSite {
            get {
                return this.WebSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebSiteField, value) != true)) {
                    this.WebSiteField = value;
                    this.RaisePropertyChanged("WebSite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanningElementWS", Namespace="http://schemas.datacontract.org/2004/07/WebServiceAgenda.Business")]
    [System.SerializableAttribute()]
    public partial class PlanningElementWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateDebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceAgenda.EvenementWS EvenementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceAgenda.LieuWS LieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NombresPlacesReserveesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateDebut {
            get {
                return this.DateDebutField;
            }
            set {
                if ((this.DateDebutField.Equals(value) != true)) {
                    this.DateDebutField = value;
                    this.RaisePropertyChanged("DateDebut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateFin {
            get {
                return this.DateFinField;
            }
            set {
                if ((this.DateFinField.Equals(value) != true)) {
                    this.DateFinField = value;
                    this.RaisePropertyChanged("DateFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceAgenda.EvenementWS Evenement {
            get {
                return this.EvenementField;
            }
            set {
                if ((object.ReferenceEquals(this.EvenementField, value) != true)) {
                    this.EvenementField = value;
                    this.RaisePropertyChanged("Evenement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceAgenda.LieuWS Lieu {
            get {
                return this.LieuField;
            }
            set {
                if ((object.ReferenceEquals(this.LieuField, value) != true)) {
                    this.LieuField = value;
                    this.RaisePropertyChanged("Lieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NombresPlacesReservees {
            get {
                return this.NombresPlacesReserveesField;
            }
            set {
                if ((this.NombresPlacesReserveesField.Equals(value) != true)) {
                    this.NombresPlacesReserveesField = value;
                    this.RaisePropertyChanged("NombresPlacesReservees");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAgenda.IServiceAgenda")]
    public interface IServiceAgenda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getAllArtistes", ReplyAction="http://tempuri.org/IServiceAgenda/getAllArtistesResponse")]
        WebApplication1.ServiceAgenda.ArtisteWS[] getAllArtistes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getAllArtistes", ReplyAction="http://tempuri.org/IServiceAgenda/getAllArtistesResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.ArtisteWS[]> getAllArtistesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getArtiste", ReplyAction="http://tempuri.org/IServiceAgenda/getArtisteResponse")]
        WebApplication1.ServiceAgenda.ArtisteWS getArtiste(string Guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getArtiste", ReplyAction="http://tempuri.org/IServiceAgenda/getArtisteResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.ArtisteWS> getArtisteAsync(string Guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getAllEvenements", ReplyAction="http://tempuri.org/IServiceAgenda/getAllEvenementsResponse")]
        WebApplication1.ServiceAgenda.EvenementWS[] getAllEvenements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getAllEvenements", ReplyAction="http://tempuri.org/IServiceAgenda/getAllEvenementsResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.EvenementWS[]> getAllEvenementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getEvenementsByArtiste", ReplyAction="http://tempuri.org/IServiceAgenda/getEvenementsByArtisteResponse")]
        WebApplication1.ServiceAgenda.EvenementWS[] getEvenementsByArtiste(WebApplication1.ServiceAgenda.ArtisteWS Artiste);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getEvenementsByArtiste", ReplyAction="http://tempuri.org/IServiceAgenda/getEvenementsByArtisteResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.EvenementWS[]> getEvenementsByArtisteAsync(WebApplication1.ServiceAgenda.ArtisteWS Artiste);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getAllLieux", ReplyAction="http://tempuri.org/IServiceAgenda/getAllLieuxResponse")]
        WebApplication1.ServiceAgenda.LieuWS[] getAllLieux();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getAllLieux", ReplyAction="http://tempuri.org/IServiceAgenda/getAllLieuxResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.LieuWS[]> getAllLieuxAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getLieuxEvents", ReplyAction="http://tempuri.org/IServiceAgenda/getLieuxEventsResponse")]
        WebApplication1.ServiceAgenda.LieuWS[] getLieuxEvents(string evenement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/getLieuxEvents", ReplyAction="http://tempuri.org/IServiceAgenda/getLieuxEventsResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.LieuWS[]> getLieuxEventsAsync(string evenement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/checkUser", ReplyAction="http://tempuri.org/IServiceAgenda/checkUserResponse")]
        bool checkUser(string login, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/checkUser", ReplyAction="http://tempuri.org/IServiceAgenda/checkUserResponse")]
        System.Threading.Tasks.Task<bool> checkUserAsync(string login, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/nbPlacesDisponible", ReplyAction="http://tempuri.org/IServiceAgenda/nbPlacesDisponibleResponse")]
        int nbPlacesDisponible(WebApplication1.ServiceAgenda.PlanningElementWS pElements);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/nbPlacesDisponible", ReplyAction="http://tempuri.org/IServiceAgenda/nbPlacesDisponibleResponse")]
        System.Threading.Tasks.Task<int> nbPlacesDisponibleAsync(WebApplication1.ServiceAgenda.PlanningElementWS pElements);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/ReserverPlace", ReplyAction="http://tempuri.org/IServiceAgenda/ReserverPlaceResponse")]
        int ReserverPlace(int nbPlaces, WebApplication1.ServiceAgenda.PlanningElementWS pElements);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/ReserverPlace", ReplyAction="http://tempuri.org/IServiceAgenda/ReserverPlaceResponse")]
        System.Threading.Tasks.Task<int> ReserverPlaceAsync(int nbPlaces, WebApplication1.ServiceAgenda.PlanningElementWS pElements);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAgendaChannel : WebApplication1.ServiceAgenda.IServiceAgenda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAgendaClient : System.ServiceModel.ClientBase<WebApplication1.ServiceAgenda.IServiceAgenda>, WebApplication1.ServiceAgenda.IServiceAgenda {
        
        public ServiceAgendaClient() {
        }
        
        public ServiceAgendaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAgendaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAgendaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAgendaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.ServiceAgenda.ArtisteWS[] getAllArtistes() {
            return base.Channel.getAllArtistes();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.ArtisteWS[]> getAllArtistesAsync() {
            return base.Channel.getAllArtistesAsync();
        }
        
        public WebApplication1.ServiceAgenda.ArtisteWS getArtiste(string Guid) {
            return base.Channel.getArtiste(Guid);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.ArtisteWS> getArtisteAsync(string Guid) {
            return base.Channel.getArtisteAsync(Guid);
        }
        
        public WebApplication1.ServiceAgenda.EvenementWS[] getAllEvenements() {
            return base.Channel.getAllEvenements();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.EvenementWS[]> getAllEvenementsAsync() {
            return base.Channel.getAllEvenementsAsync();
        }
        
        public WebApplication1.ServiceAgenda.EvenementWS[] getEvenementsByArtiste(WebApplication1.ServiceAgenda.ArtisteWS Artiste) {
            return base.Channel.getEvenementsByArtiste(Artiste);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.EvenementWS[]> getEvenementsByArtisteAsync(WebApplication1.ServiceAgenda.ArtisteWS Artiste) {
            return base.Channel.getEvenementsByArtisteAsync(Artiste);
        }
        
        public WebApplication1.ServiceAgenda.LieuWS[] getAllLieux() {
            return base.Channel.getAllLieux();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.LieuWS[]> getAllLieuxAsync() {
            return base.Channel.getAllLieuxAsync();
        }
        
        public WebApplication1.ServiceAgenda.LieuWS[] getLieuxEvents(string evenement) {
            return base.Channel.getLieuxEvents(evenement);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceAgenda.LieuWS[]> getLieuxEventsAsync(string evenement) {
            return base.Channel.getLieuxEventsAsync(evenement);
        }
        
        public bool checkUser(string login, string mdp) {
            return base.Channel.checkUser(login, mdp);
        }
        
        public System.Threading.Tasks.Task<bool> checkUserAsync(string login, string mdp) {
            return base.Channel.checkUserAsync(login, mdp);
        }
        
        public int nbPlacesDisponible(WebApplication1.ServiceAgenda.PlanningElementWS pElements) {
            return base.Channel.nbPlacesDisponible(pElements);
        }
        
        public System.Threading.Tasks.Task<int> nbPlacesDisponibleAsync(WebApplication1.ServiceAgenda.PlanningElementWS pElements) {
            return base.Channel.nbPlacesDisponibleAsync(pElements);
        }
        
        public int ReserverPlace(int nbPlaces, WebApplication1.ServiceAgenda.PlanningElementWS pElements) {
            return base.Channel.ReserverPlace(nbPlaces, pElements);
        }
        
        public System.Threading.Tasks.Task<int> ReserverPlaceAsync(int nbPlaces, WebApplication1.ServiceAgenda.PlanningElementWS pElements) {
            return base.Channel.ReserverPlaceAsync(nbPlaces, pElements);
        }
    }
}
